[build]
  command = "npm run build"  # Commande pour construire le projet
  publish = "dist"           # Répertoire à publier après la construction

[build.environment]
  NODE_ENV = "production"   # Assurez-vous que l'environnement est défini pour la production

[[redirects]]
  from = "/vite.svg"
  to = "/vite.svg"
  status = 200
